//
// ParserAction.cpp
// Copyright (c) Charles Baker. All rights reserved.
//

#define __STDC_WANT_LIB_EXT2__ 1 // To get `strdup()`

#include "ParserAction.hpp"
#include "assert.hpp"
#include <string.h>

using namespace sweet::lalr;

/**
// Default constructor
*/
ParserAction::ParserAction()
: index( 0 ),
  identifier( nullptr )
{
}

/**
// Free memory allocated by this `ParserAction`.
//
// Memory is freed selectively in `ParserAction::destroy()` rather than in
// `~ParserAction` because `ParserAction` objects may also be defined as 
// static data generated by the parser generator `lalrc`.  `ParserAction` 
// objects that are created at run-time are explicitly destroyed by their
// owning `Grammar`, `LalrGenerator`, or `ParserStateMachine`.
*/
ParserAction::~ParserAction()
{
    if ( identifier )
    {
        free( (void*) identifier );
        identifier = nullptr;
    }
}

void ParserAction::reset( int iindex, const char* iidentifier )
{
    SWEET_ASSERT( !identifier );
    SWEET_ASSERT( iindex >= 0 );
    SWEET_ASSERT( iidentifier );
    index = iindex;
    identifier = strdup( iidentifier );
}
