
#pragma once

#define WIN32_LEAN_AND_MEAN
#define _CRT_SECURE_NO_DEPRECATE
#define _SCL_SECURE_NO_DEPRECATE
#define NOMINMAX
#define BOOST_SPIRIT_USE_OLD_NAMESPACE

/*
#define BOOST_SPIRIT_DEBUG
*/
